version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z
    container_name: _REPLACE_MINIO_CONTAINER_NAME_HERE_
    ports:
      - _REPLACE_MINIO_BUCKET_PORT_HERE_:9000
      - _REPLACE_MINIO_ADMIN_PORT_HERE_:9001
    environment:
      MINIO_ROOT_USER: _REPLACE_MINIO_ROOT_USER_HERE_
      MINIO_ROOT_PASSWORD: _REPLACE_MINIO_ROOT_PASSWORD_HERE_
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio/
    command: server --console-address ':9001' /data
