version: "3"

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    container_name: _REPLACE_POSTGRESQL_CONTAINER_NAME_HERE_
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - "_REPLACE_POSTGRE_PORT_HERE_:5432"
    volumes:
      - ./postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: _REPLACE_POSTGRE_USERNAME_HERE_
      POSTGRES_PASSWORD: _REPLACE_POSTGRE_PASSWORD_HERE_
